version: "3.7"
services:
  api_service:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/herbal?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: herbal 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
      
  react-app:
    build:
      context: ../sshkey  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - springapimysql-net

networks:
  springapimysql-net: