version: '3.8'
services:
  app:
    image: herbal
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/herbal?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=herbal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
