version: "3.3"

services:
  api_service:
    build: .
    restart: always
    ports:
      - "9000:9000"
    networks:
      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/herbal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: herbal
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 

networks:
  springapimysql-net:
